version: '3'

services:
  m1:
    image: redis:7
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/m1.conf:/usr/local/etc/redis/redis.conf

  s1:
    image: redis:7
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/s1.conf:/usr/local/etc/redis/redis.conf

      


volumes:
  redis:
  