version: '3'

services:
  app:
    image: ruby:3.1
    volumes:
      - .:/usr/src/app
  m1:
    image: redis:7
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/m1.conf:/usr/local/etc/redis/redis.conf
      - ./data/m1:/data

  s1:
    image: redis:7
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/s1.conf:/usr/local/etc/redis/redis.conf
      - ./data/s1:/data

  s2:
    image: redis:7
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/s2.conf:/usr/local/etc/redis/redis.conf
      - ./data/s2:/data

  st1:
    image: redis:7
    command: 'redis-sentinel /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/st1.conf:/usr/local/etc/redis/redis.conf
      - ./data/st1:/data
    depends_on:
      - m1
      - s1
      - s2

  st2:
    image: redis:7
    command: 'redis-sentinel /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/st2.conf:/usr/local/etc/redis/redis.conf
      - ./data/st2:/data
    depends_on:
      - m1
      - s1
      - s2
  st3:
    image: redis:7
    command: 'redis-sentinel /usr/local/etc/redis/redis.conf'
    volumes:
      - ./conf/st3.conf:/usr/local/etc/redis/redis.conf
      - ./data/st3:/data
    depends_on:
      - m1
      - s1
      - s2

      


volumes:
  redis:
  